apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-mongodb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-mongodb-deployment
  template:
    metadata:
      labels:
        app: flask-mongodb-deployment
    spec:
      containers:
        - name: flask-app
          image: jrdeveloper06/python-crud:latest
          ports:
            - containerPort: 5000
        - name: mongo
          image: mongo:latest
          ports:
            - containerPort: 27017

---
apiVersion: v1
kind: Service
metadata:
  name: my-mongo
spec:
  selector:
    app: flask-mongodb-deployment
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: my-flask-app-service
spec:
  selector:
    app: flask-mongodb-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: NodePort
